apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: elemental-rpi4-demo-ams
  namespace: fleet-default
spec:
  kubernetesVersion: v1.23.16+k3s1
  rkeConfig:
    machineGlobalConfig:
      disable-apiserver: false
      disable-cloud-controller: false
      disable-controller-manager: false
      disable-etcd: false
      disable-kube-proxy: false
      disable-network-policy: false
      disable-scheduler: false
      etcd-expose-metrics: false
      profile: null
      secrets-encryption: false
    machinePools:
      - controlPlaneRole: true
        drainBeforeDelete: true
        etcdRole: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: rpi-dot-matrix
        name: pool1
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
          selinux: false
    registries: {}
