apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: rpi-dot-matrix
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
          - key: "acme.corp/city"
            operator: In
            values: [ "ams" ]
