apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: rpi-dotmatrix-machine-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
          - key: "gpio.hardware.io/dotmatrix-model"
            operator: In
            values: [ "adafruit64" ]