kind: Deployment
apiVersion: apps/v1
metadata:
  name: elemental-dotmatrix-demo
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dotmatrix-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dotmatrix-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dotmatrix-demo
    spec:
      terminationGracePeriodSeconds: 15
      volumes:
        - name: rpi-gpio
          hostPath:
            path: /dev/gpiomem
        - name: osrelease
          hostPath:
            path: /etc/os-release
      containers:
        - name: dotmatrix-demo
          volumeMounts:
            - name: rpi-gpio
              mountPath: /dev/gpiomem
            - name: osrelease
              mountPath: /etc/os-release
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.app.image.image }}:{{ .Values.app.image.tag }}"
          securityContext:
            privileged: true
          env:
          {{- if .Values.hw.dotmatrixoptions }}
          - name: MATRIX_OPTS
            value: {{ .Values.hw.dotmatrixoptions | quote }}
          {{- end }}
          {{- if .Values.metadata.cluster }}
          - name: CLUSTER_NAME
            value: {{ .Values.metadata.cluster  | quote }}
          {{- end }}