kind: Deployment
apiVersion: apps/v1
metadata:
  name: elemental-dotmatrix-demo
  namespace: elemental-demo
  labels:
    app.kubernetes.io/name: dotmatrix-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dotmatrix-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dotmatrix-demo
    spec:
      terminationGracePeriodSeconds: 15
      volumes:
        - name: rpi-gpio
          hostPath:
            path: /dev/gpiomem
        - name: osrelease
          hostPath:
            path: /etc/os-release
      containers:
        - name: dotmatrix-demo
          volumeMounts:
            - name: rpi-gpio
              mountPath: /dev/gpiomem
            - name: osrelease
              mountPath: /etc/os-release
          imagePullPolicy: IfNotPresent
          image: "janeczku/elemental-dotmatrix-demo:v0.1.0"
          securityContext:
            privileged: true
          env:
          - name: MATRIX_OPTS
            value: "--led-no-hardware-pulse --led-cols=64 --led-rows=64 --led-gpio-mapping=adafruit-hat --led-brightness=80"
